name: osx-run tests
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get update && sudo apt-get install -y shellcheck
    - run: shellcheck -e SC1091 osx-run/osx-run.sh osx-run/tests/*.sh
    - run: ./osx-run/tests/run-tests.sh
